version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(npm dep)"
      prefix-development: "chore(npm dev dep)"
      include: "scope"
